AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TheBestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PolarisFocusAPI
      StageName: Testing
    Metadata:
      SamResourceId: TheBestApi
  TrackerGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tracker_get_sam
      Handler: TrackerGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/7cd01f0ea186ebe8cf7eddb8b541a575
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Counters
          COUNTER_NAME: EventParseAmount
      Events:
        TrackerGetEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /tracker/event/get
            Method: GET
    Metadata:
      SamResourceId: TrackerGetFunction
  EventStreamReaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stream_reader_sam
      Handler: StreamReader
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/e2b948ed3ad5e48b3bfc037db66a85a1
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
    Metadata:
      SamResourceId: EventStreamReaderFunction
  UcfEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ucf_events_sam
      Handler: UCFEvents
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/00ff06533b8e15f64d0e95dcd62acbdf
      MemorySize: 256
      Timeout: 20
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
          ADVANCE_PAGES: 2
    Metadata:
      SamResourceId: UcfEventsFunction
  KnightsParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: knights_parser_sam
      Handler: KnightsConnect
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/7b538752aa2207f65b2a50e7e606511b
      MemorySize: 256
      Timeout: 20
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
          ADVANCE_DAYS: 5
    Metadata:
      SamResourceId: KnightsParserFunction
  BuildingAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: location_add_sam
      Handler: BuildingAdd
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/92614dcf401e4ae4d99c4361c276a89b
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingAddEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/add
            Method: POST
    Metadata:
      SamResourceId: BuildingAddFunction
  BuildingGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_get_sam
      Handler: BuildingGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/f1a841441eb9a8ba29e7d5894f6b86a5
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingAddEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/get
            Method: POST
    Metadata:
      SamResourceId: BuildingGetFunction
  BuildingUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_update_sam
      Handler: BuildingUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/95c2f503ebee91c20eee7ddd9e02a708
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingUpdateEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/update
            Method: POST
    Metadata:
      SamResourceId: BuildingUpdateFunction
  BuildingDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_delete_sam
      Handler: BuildingDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/1acad8f92af93e4eb677a2f3b87f8598
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingDeleteEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/delete
            Method: DELETE
    Metadata:
      SamResourceId: BuildingDeleteFunction
  BuildingScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: location_scan_sam
      Handler: Scan
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/de7b394607b6f6c0e21421e90ec64844
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingScanEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/scan
            Method: POST
    Metadata:
      SamResourceId: BuildingScanFunction
  EventGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_get_sam
      Handler: EventGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/342910656d0855cf3da62f9ca9497c6c
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        GetEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/get
            Method: POST
    Metadata:
      SamResourceId: EventGetFunction
  EventAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_add_sam
      Handler: EventsAdd
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/4697fcaac84bffc9ddc17259a6ae84f7
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        AddEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/add
            Method: POST
    Metadata:
      SamResourceId: EventAddFunction
  EventUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_update_sam
      Handler: EventsUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/79f3dc38be6e854b3fba61c668b36a39
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        UpdateEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/update
            Method: POST
    Metadata:
      SamResourceId: EventUpdateFunction
  EventScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_scan_sam
      Handler: Scan
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/de7b394607b6f6c0e21421e90ec64844
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        ScanEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/scan
            Method: POST
    Metadata:
      SamResourceId: EventScanFunction
  EventDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_delete_sam
      Handler: EventDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/f164ee93feaedf6c676a1506bde93cfd
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        DeleteEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/delete
            Method: DELETE
    Metadata:
      SamResourceId: EventDeleteFunction
  EventQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_query_sam
      Handler: EventsScan
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/3ca708ea40ba66ae0d78c4ac3be8315a
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        QueryEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/query
            Method: POST
    Metadata:
      SamResourceId: EventQueryFunction
  UserRegistrationCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_registration_code_sam
      Handler: RegistrationCode
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/a7c6f9d1ad939a873015fb043c1bbade
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserRegistrationCodeEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/registrationcode
            Method: POST
    Metadata:
      SamResourceId: UserRegistrationCodeFunction
  UserRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_register_sam
      Handler: Register
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/ebc670e059d186f63e6626ac398b50b7
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserRegisterEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/register
            Method: POST
    Metadata:
      SamResourceId: UserRegisterFunction
  UserLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_verify_sam
      Handler: Login
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/4b3b845b8e7ed43c6a406aa13a6f4d17
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserLoginEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/login
            Method: POST
    Metadata:
      SamResourceId: UserLoginFunction
  UserGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_get_sam
      Handler: UserGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/515737127414646e646e39e97e31a078
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserGetEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/get
            Method: POST
    Metadata:
      SamResourceId: UserGetFunction
  UserUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_update_sam
      Handler: UserUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/5f739858dba7a5e8439b03fe1c516584
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserUpdateEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/update
            Method: PUT
    Metadata:
      SamResourceId: UserUpdateFunction
  UserDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_delete_sam
      Handler: UserDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/5ff5d3875967089a1039acc1d5fa48c2
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserDeleteEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/delete
            Method: DELETE
    Metadata:
      SamResourceId: UserDeleteFunction
  UserResetPasswordCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_reset_password_code_sam
      Handler: ResetPasswordCode
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/5701d8108e9dbc0835be2d0b8b3564c0
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserResetPasswordCodeEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/passwordresetcode
            Method: POST
    Metadata:
      SamResourceId: UserResetPasswordCodeFunction
  UserResetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_reset_password_sam
      Handler: PasswordReset
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/200f078a75471da6034505f185beac5d
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserResetPasswordEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/passwordreset
            Method: POST
    Metadata:
      SamResourceId: UserResetPasswordFunction
