AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TheBestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PolarisFocusAPI
      StageName: Testing
    Metadata:
      SamResourceId: TheBestApi
  TrackerGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tracker_get_sam
      Handler: TrackerGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/0b4fbb1643111c4f2fdd0ae8f21f13ec
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Counters
          COUNTER_NAME: EventParseAmount
      Events:
        TrackerGetEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /tracker/event/get
            Method: GET
    Metadata:
      SamResourceId: TrackerGetFunction
  EventStreamReaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stream_reader_sam
      Handler: StreamReader
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/ef8e53178fb4e36178bd5d1486af6bc5
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
    Metadata:
      SamResourceId: EventStreamReaderFunction
  UcfEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ucf_events_sam
      Handler: UCFEvents
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/32673eeb9bef85169ca25b19b1d5bac8
      MemorySize: 256
      Timeout: 20
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
          ADVANCE_PAGES: 2
    Metadata:
      SamResourceId: UcfEventsFunction
  KnightsParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: knights_parser_sam
      Handler: KnightsConnect
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/0e9e76c0514d6c396ceb561a91cbaf90
      MemorySize: 256
      Timeout: 20
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
          ADVANCE_DAYS: 5
    Metadata:
      SamResourceId: KnightsParserFunction
  BuildingAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: location_add_sam
      Handler: BuildingAdd
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/e6a62c57408712ea4d6a2a894ac60ec5
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingAddEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/add
            Method: POST
    Metadata:
      SamResourceId: BuildingAddFunction
  BuildingGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_get_sam
      Handler: BuildingGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/105539d2458c62cae89e84c18315edeb
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingAddEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/get
            Method: POST
    Metadata:
      SamResourceId: BuildingGetFunction
  BuildingUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_update_sam
      Handler: BuildingUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/6d8c7e42e4f954a0c1de274333a8eb14
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingUpdateEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/update
            Method: POST
    Metadata:
      SamResourceId: BuildingUpdateFunction
  BuildingDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_delete_sam
      Handler: BuildingDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/8303c32d1e8f01b4579e8faed2569d67
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingDeleteEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/delete
            Method: DELETE
    Metadata:
      SamResourceId: BuildingDeleteFunction
  BuildingScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: location_scan_sam
      Handler: Scan
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/9dde6abae17b3a5f0605824e55d7fb68
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingScanEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/scan
            Method: POST
    Metadata:
      SamResourceId: BuildingScanFunction
  EventGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_get_sam
      Handler: EventGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/db06a7889a415207995bbd594e141a1a
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        GetEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/get
            Method: POST
    Metadata:
      SamResourceId: EventGetFunction
  EventAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_add_sam
      Handler: EventsAdd
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/bacb349706ac37832aac96da7932d10d
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        AddEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/add
            Method: POST
    Metadata:
      SamResourceId: EventAddFunction
  EventUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_update_sam
      Handler: EventsUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/59afdbbdc7b1bad100d34d4dc3efa7ff
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        UpdateEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/update
            Method: POST
    Metadata:
      SamResourceId: EventUpdateFunction
  EventScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_scan_sam
      Handler: Scan
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/9dde6abae17b3a5f0605824e55d7fb68
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        ScanEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/scan
            Method: POST
    Metadata:
      SamResourceId: EventScanFunction
  EventDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_delete_sam
      Handler: EventDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/cf1b0baa577c33af629bb601eab5ba75
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        DeleteEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/delete
            Method: DELETE
    Metadata:
      SamResourceId: EventDeleteFunction
  EventQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_query_sam
      Handler: EventsScan
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/d53dd76460e967f9aff1eef28e7e6436
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        QueryEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/query
            Method: POST
    Metadata:
      SamResourceId: EventQueryFunction
  UserRegistrationCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_registration_code_sam
      Handler: RegistrationCode
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/d53fb2de816bf1964d138c0b61a9b446
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserRegistrationCodeEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/registrationcode
            Method: POST
    Metadata:
      SamResourceId: UserRegistrationCodeFunction
  UserRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_register_sam
      Handler: Register
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/92fbcd9090fda34353cd82f078808bff
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserRegisterEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/register
            Method: POST
    Metadata:
      SamResourceId: UserRegisterFunction
  UserLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_verify_sam
      Handler: Login
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/ebaea17bd0ab452a07d8999124b5125a
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserLoginEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/login
            Method: POST
    Metadata:
      SamResourceId: UserLoginFunction
  UserGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_get_sam
      Handler: UserGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/08744b026d5ec73e8200962d245b1f32
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserGetEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/get
            Method: POST
    Metadata:
      SamResourceId: UserGetFunction
  UserUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_update_sam
      Handler: UserUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/fa75df7c0bb5a9e7e34f09d49b9f297a
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserUpdateEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/update
            Method: PUT
    Metadata:
      SamResourceId: UserUpdateFunction
  UserDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_delete_sam
      Handler: UserDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/8aacdbefb927c528ac7e443d606b89de
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserDeleteEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/delete
            Method: DELETE
    Metadata:
      SamResourceId: UserDeleteFunction
  UserResetPasswordCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_reset_password_code_sam
      Handler: ResetPasswordCode
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/c9d8bad174db49c1694f8ed7a1646183
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserResetPasswordCodeEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/passwordresetcode
            Method: POST
    Metadata:
      SamResourceId: UserResetPasswordCodeFunction
  UserResetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_reset_password_sam
      Handler: PasswordReset
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/e36dd3c90a0c58f6126c19d2745eb5c6
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserResetPasswordEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/passwordreset
            Method: POST
    Metadata:
      SamResourceId: UserResetPasswordFunction
