AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TheBestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PolarisAPI
      StageName: Testing
      Auth:
        DefaultAuthorizer: JwtAuthorizer
        Authorizers:
          JwtAuthorizer:
            FunctionArn:
              Ref: JwtAuthorizerFunction
          JwtAuthorizerRegister:
            FunctionArn:
              Ref: JwtAuthorizerRegisterFunction
    Metadata:
      SamResourceId: TheBestApi
  JwtAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: jwt_authorizer_sam
      Handler: TokenVerify
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/e12606954120e521b985e69c3afce719
      MemorySize: 256
      Timeout: 10
    Metadata:
      SamResourceId: JwtAuthorizerFunction
  JwtAuthorizerRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: jwt_authorizer_register_sam
      Handler: TokenVerify
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/e12606954120e521b985e69c3afce719
      MemorySize: 256
      Timeout: 10
    Metadata:
      SamResourceId: JwtAuthorizerRegisterFunction
  BuildingAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: location_add_sam
      Handler: BuildingAdd
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/2232b457dd7b2d5c55efffbebb7548d2
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingAddEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/add
            Method: POST
            Auth:
              Authorizer: JwtAuthorizer
    Metadata:
      SamResourceId: BuildingAddFunction
  BuildingGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_get_sam
      Handler: BuildingGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/f4aa51e1a54931d958211bb49ccaffc3
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingAddEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/get
            Method: POST
    Metadata:
      SamResourceId: BuildingGetFunction
  BuildingUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_update_sam
      Handler: BuildingUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/44d432541ba835300eb471cb50f3677e
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingUpdateEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/update
            Method: POST
    Metadata:
      SamResourceId: BuildingUpdateFunction
  BuildingDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_delete_sam
      Handler: BuildingDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/898514fbab87aef8292d4a5d84f115ca
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingDeleteEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/delete
            Method: DELETE
    Metadata:
      SamResourceId: BuildingDeleteFunction
  BuildingQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: location_query_sam
      Handler: BuildingQuery
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/b8a3069f6fb5452336f533e0941b0f1d
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingQueryEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/query
            Method: POST
    Metadata:
      SamResourceId: BuildingQueryFunction
  EventGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_get_sam
      Handler: EventGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/5f8137b09aa6327f435694f19be325ab
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        GetEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/get
            Method: POST
    Metadata:
      SamResourceId: EventGetFunction
  EventAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_add_sam
      Handler: EventsAdd
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/b26190dd230805ad1e566d7aeb33c7dd
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        AddEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/add
            Method: POST
    Metadata:
      SamResourceId: EventAddFunction
  EventUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_update_sam
      Handler: EventsUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/8571ab2ab5fc9608766fc4f5591a9a0f
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        UpdateEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/update
            Method: POST
    Metadata:
      SamResourceId: EventUpdateFunction
  EventQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_query_sam
      Handler: EventsQuery
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/d6acd5b8df05e2abaeb0e52570a3b299
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        QueryEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/query
            Method: POST
    Metadata:
      SamResourceId: EventQueryFunction
  EventDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_delete_sam
      Handler: EventDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/2a2260e81cd39718ebf9deb1f3e3b8cd
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        DeleteEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/delete
            Method: DELETE
    Metadata:
      SamResourceId: EventDeleteFunction
  UserRegistrationCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_registration_code_sam
      Handler: RegistrationCode
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/a1c94d7b59a3e4995e1b09ed57ec9513
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserRegistrationCodeEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/registrationcode
            Method: POST
    Metadata:
      SamResourceId: UserRegistrationCodeFunction
  UserRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_register_sam
      Handler: Register
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/82cdde71dc2b06940be2d225d1ac5b5a
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserRegisterEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/register
            Method: POST
    Metadata:
      SamResourceId: UserRegisterFunction
  UserLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_verify_sam
      Handler: Login
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/5d54208b979b2cad6bf9bf751a98a32a
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserLoginEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/login
            Method: POST
    Metadata:
      SamResourceId: UserLoginFunction
  UserGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_get_sam
      Handler: UserGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/77954ff4cf13adeba7584efefa5932bf
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserGetEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/get
            Method: POST
    Metadata:
      SamResourceId: UserGetFunction
  UserUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_update_sam
      Handler: UserUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/e594924be21ff71e2379521fadc68747
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserUpdateEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/update
            Method: PUT
    Metadata:
      SamResourceId: UserUpdateFunction
  UserDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_delete_sam
      Handler: UserDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/db376ff10a2032adf667ab63f249857f
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserDeleteEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/delete
            Method: DELETE
    Metadata:
      SamResourceId: UserDeleteFunction
