AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TheBestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PolarisAPI
      StageName: Testing
    Metadata:
      SamResourceId: TheBestApi
  BuildingAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: location_add_sam
      Handler: BuildingAdd
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/3a1ef48b4976448115f9d1c79ff35593
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingAddEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/add
            Method: POST
    Metadata:
      SamResourceId: BuildingAddFunction
  BuildingGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_get_sam
      Handler: BuildingGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/c647af493502f21fd308760319c72ac2
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingAddEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/get
            Method: POST
    Metadata:
      SamResourceId: BuildingGetFunction
  BuildingUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_update_sam
      Handler: BuildingUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/a1fcf0076e63337b237b09bc041f676e
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingUpdateEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/update
            Method: POST
    Metadata:
      SamResourceId: BuildingUpdateFunction
  BuildingDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_delete_sam
      Handler: BuildingDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/3d3835ee16c5f6f89895f6a93f1e47e8
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingDeleteEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/delete
            Method: DELETE
    Metadata:
      SamResourceId: BuildingDeleteFunction
  BuildingQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: location_query_sam
      Handler: BuildingQuery
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/f63c11376ad05bd5d2b52439ba9ad7c6
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Buildings
      Events:
        BuildingQueryEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /building/query
            Method: POST
    Metadata:
      SamResourceId: BuildingQueryFunction
  EventGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_get_sam
      Handler: EventGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/49b16bdac1ef2a2159653074b65935e7
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        GetEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/get
            Method: POST
    Metadata:
      SamResourceId: EventGetFunction
  EventAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_add_sam
      Handler: EventsAdd
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/c0f89cd339968f6916b8fd443493f98b
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        AddEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/add
            Method: POST
    Metadata:
      SamResourceId: EventAddFunction
  EventUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_update_sam
      Handler: EventsUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/84624cc079946aa938520553681b8c16
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        UpdateEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/update
            Method: POST
    Metadata:
      SamResourceId: EventUpdateFunction
  EventQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_query_sam
      Handler: EventsQuery
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/0dcb2ada4067f4d17436d670df7d76de
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        QueryEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/query
            Method: POST
    Metadata:
      SamResourceId: EventQueryFunction
  EventDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_delete_sam
      Handler: EventDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/5ba1e6d07bc842cab4bab933c5c38fa7
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Events
      Events:
        DeleteEventEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /event/delete
            Method: DELETE
    Metadata:
      SamResourceId: EventDeleteFunction
  UserRegistrationCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_registration_code_sam
      Handler: RegistrationCode
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/626dc5ebf8e7c01881697b0ed279f999
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserRegistrationCodeEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/registrationcode
            Method: POST
    Metadata:
      SamResourceId: UserRegistrationCodeFunction
  UserRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_register_sam
      Handler: LambdaUserCreate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/da53463cc9fe83fc0a8332565c5aeffa
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserRegisterEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/register
            Method: POST
    Metadata:
      SamResourceId: UserRegisterFunction
  UserLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_verify_sam
      Handler: LambdaVerify
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/3d44d784f807584335f24093a4c6b963
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserLoginEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/login
            Method: POST
    Metadata:
      SamResourceId: UserLoginFunction
  UserGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_get_sam
      Handler: UserGet
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/fd4a523bdb021d43bc4dae0ace127825
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserGetEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/get
            Method: POST
    Metadata:
      SamResourceId: UserGetFunction
  UserUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_update_sam
      Handler: UserUpdate
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/c66ffd23d9f078c40a9f35163b7d3e41
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserUpdateEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/update
            Method: PUT
    Metadata:
      SamResourceId: UserUpdateFunction
  UserDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_delete_sam
      Handler: UserDelete
      Runtime: go1.x
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-ri5k5ky9x3uv/b318f5bb9f77eda6476dc1937fe020b3
      MemorySize: 256
      Timeout: 10
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: Users
      Events:
        UserDeleteEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: TheBestApi
            Path: /user/delete
            Method: DELETE
    Metadata:
      SamResourceId: UserDeleteFunction
