AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
# --- DEFINE API RESOURCE ---
  TheBestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PolarisFocusAPI
      StageName: Testing

# --- STREAM FUNCTION ---
  EventStreamReaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stream_reader_sam
      Handler: StreamReader
      Runtime: go1.x
      CodeUri: StreamReader/StreamReader
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Buildings"

# --- BUILDING FUNCTIONS ---
  BuildingAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: location_add_sam
      Handler: BuildingAdd
      Runtime: go1.x
      CodeUri: LocationEndpoints/BuildingAdd
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Buildings"
      Events:
        BuildingAddEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /building/add
            Method: POST
  BuildingGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_get_sam
      Handler: BuildingGet
      Runtime: go1.x
      CodeUri: LocationEndpoints/BuildingGet
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Buildings"
      Events:
        BuildingAddEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /building/get
            Method: POST
  BuildingUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_update_sam
      Handler: BuildingUpdate
      Runtime: go1.x
      CodeUri: LocationEndpoints/BuildingUpdate
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Buildings"
      Events:
        BuildingUpdateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /building/update
            Method: POST
  BuildingDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: building_delete_sam
      Handler: BuildingDelete
      Runtime: go1.x
      CodeUri: LocationEndpoints/BuildingDelete
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Buildings"
      Events:
        BuildingDeleteEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /building/delete
            Method: DELETE
  BuildingScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: location_scan_sam
      Handler: Scan
      Runtime: go1.x
      CodeUri: Scan/Scan
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Buildings"
      Events:
        BuildingScanEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /building/scan
            Method: POST

# --- EVENT FUNCTIONS ---
  EventGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_get_sam
      Handler: EventGet
      Runtime: go1.x
      CodeUri: EventEndpoints/EventGet
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Events"
      Events:
        GetEventEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /event/get
            Method: POST
  EventAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_add_sam
      Handler: EventsAdd
      Runtime: go1.x
      CodeUri: EventEndpoints/EventsAdd
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Events"
      Events:
        AddEventEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /event/add
            Method: POST
  EventUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_update_sam
      Handler: EventsUpdate
      Runtime: go1.x
      CodeUri: EventEndpoints/EventsUpdate
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Events"
      Events:
        UpdateEventEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /event/update
            Method: POST
  EventScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_scan_sam
      Handler: EventsScan
      Runtime: go1.x
      CodeUri: Scan/Scan
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Events"
      Events:
        ScanEventEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /event/scan
            Method: POST
  EventDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_delete_sam
      Handler: EventDelete
      Runtime: go1.x
      CodeUri: EventEndpoints/EventsDelete
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Events"
      Events:
        DeleteEventEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /event/delete
            Method: DELETE
  EventQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: event_query_sam
      Handler: EventsScan
      Runtime: go1.x
      CodeUri: EventEndpoints/EventsQuery
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Events"
      Events:
        QueryEventEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /event/query
            Method: POST

# --- USER FUNCTIONS ---
  # Registration Code
  UserRegistrationCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_registration_code_sam
      Handler: RegistrationCode
      Runtime: go1.x
      CodeUri: UserEndpoints/RegistrationCode
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Users"
      Events:
        UserRegistrationCodeEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /user/registrationcode
            Method: POST
  # Register
  UserRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_register_sam
      Handler: Register
      Runtime: go1.x
      CodeUri: UserEndpoints/Register
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Users"
      Events:
        UserRegisterEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /user/register
            Method: POST
  UserLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_verify_sam
      Handler: Login
      Runtime: go1.x
      CodeUri: UserEndpoints/Login
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Users"
      Events:
        UserLoginEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /user/login
            Method: POST
  # User Get
  UserGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_get_sam
      Handler: UserGet
      Runtime: go1.x
      CodeUri: UserEndpoints/UserGet
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Users"
      Events:
        UserGetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /user/get
            Method: POST
  # User Update
  UserUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_update_sam
      Handler: UserUpdate
      Runtime: go1.x
      CodeUri: UserEndpoints/UserUpdate
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Users"
      Events:
        UserUpdateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /user/update
            Method: PUT
  UserDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: user_delete_sam
      Handler: UserDelete
      Runtime: go1.x
      CodeUri: UserEndpoints/UserDelete
      MemorySize: 256
      Timeout: 10
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
      Environment:
        Variables:
          TABLE_NAME: "Users"
      Events:
        UserDeleteEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TheBestApi
            Path: /user/delete
            Method: DELETE